# -*- coding: utf-8 -*-
"""heatmaps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cO_QU_Jpbmt5lESVQHYtW7m7PrCHpjzl
"""

#import libraries 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

#convert data a Data frame. save in df
data=pd.read_csv(r"dataNew.csv")
df = pd.DataFrame(data)
print(data.head())
data.describe()
print (data.shape)
print(data.dtypes)

#result, heatmap. It can be seen that store B is the most feasible due to the number of people who came to the place.
sns.heatmap(df)